### PR TITLE
Feature: Add Git Undo Command

### PR DESCRIPTION
**Pull request by kevintraver**

### CODE REVIEW

**Comment by chrisgrieser** [comment]
Hmm, yeah, something as simple as this should be fine. Add it also to the readme and I can merge that

**Comment by kevintraver** [comment]
I changed it to use `git reset --mixed HEAD~` which I think is a good compromise. I might add `--soft` and `--hard` as options later if I find it useful.

**Comment by chrisgrieser** [comment]
Hmm, thinking about it, I think "undo" is a bit too generic of a name. Maybe something like "undoLastCommit"?

**Comment by chrisgrieser** [comment]
lgtm!

**Pull request merged**
